export const COACHING_RULES = [
  {
    id: "minor-b-playing-time",
    title: "Playing time rotation",
    summary: "During preseason and regular-season games, each player present and not held out for disciplinary reasons must sit one inning before anyone sits a second. Division Championship players must play at least six defensive outs per game, unless the Board adopts different District 62 TOC rules.",
    section: "Section X.A.1–2",
    page: 26,
    sourceLabel: "2026 HVLL Bylaws",
    sourceUrl: "https://dt5602vnjxv0c.cloudfront.net/portals/20562/docs/2026/2026%20hvll%20bylaws.pdf#page=26",
    division: "Minor B",
    verification: "Source checked · Coach review pending",
  },
  {
    id: "minor-b-batting-order",
    title: "Continuous batting order",
    summary: "All eligible players present bat continuously through the roster, regardless of who is playing defense. Sitting a defensive inning does not remove a player from the batting order.",
    section: "Section X.E",
    page: 26,
    sourceLabel: "2026 HVLL Bylaws",
    sourceUrl: "https://dt5602vnjxv0c.cloudfront.net/portals/20562/docs/2026/2026%20hvll%20bylaws.pdf#page=26",
    division: "Minor B",
    verification: "Source checked · Coach review pending",
  },
  {
    id: "minor-b-pitching-innings",
    title: "Pitching innings",
    summary: "During the regular season, a player may pitch at most three innings per game and six per Monday–Sunday week. Throwing one pitch counts as an inning pitched. Division Championship has no daily or weekly inning limit. Little League pitch-count and rest regulations always apply separately.",
    section: "Section X.K.3–5",
    page: 27,
    sourceLabel: "2026 HVLL Bylaws",
    sourceUrl: "https://dt5602vnjxv0c.cloudfront.net/portals/20562/docs/2026/2026%20hvll%20bylaws.pdf#page=27",
    division: "Minor B",
    verification: "Source checked · Coach review pending",
  },
];
